### ISSUE TITLE
Could I make a component?

### ISSUE THREAD

**Issue by priyank-purohit** [malaman/jQuery-QueryBuilder-react-integration-example#1]
Hi,
I'm new to React.js, trying to make a <QueryBuilder /> component instead of putting this in the public index.html file of my app. I tried to do it but $(element).queryBuilder({ filters, rules });  leads to error because queryBuilder is only available in the index.html file. How could I solve this? Any help would be greatly appreciated!

**Comment by malaman** [comment]
Hi. 
Send a link to a test repo. I will take a look.

**Comment by priyank-purohit** [comment]
https://github.com/priyank-purohit/ReactComponentQueryBuilder

The QueryBuilder.js is child of MiddlePane.js ... I removed the other unnecessary code. Ideally, I want to be able to update the rules available in the query builder on state change, this I don't think I can do if I were to include the code in the index.html the way you demonstrated. I'd appreciate any help, kinda new to React..!

**Comment by malaman** [comment]
I've opened PR in your repository with small fixes.
